<h1> NUMPY </H1>

In [3]:
import numpy as np

In [2]:
li=[1,2,3]

<h3> we can cast a list in numpy array </h3>

In [3]:
np.array(li)

array([1, 2, 3])

In [5]:
'''
We can also assing numpy array to a variable
'''

'\nWe can also assing numpy array to a variable\n'

In [6]:
arr=np.array(li)

In [7]:
arr

array([1, 2, 3])

<p> we can cast a list of list in two dimension array or matrix using <b>numpy</b> but counts of index should be same otherwise it will display separate list</p>

In [16]:
list_of_list =[[1,2,3],[4,5,6],[7,8,9]]

In [17]:
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
matrix=np.array(list_of_list)

In [19]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
unlisted=[[1,2,3],[4,5,6],[1,2]]

In [22]:
 unlisted

[[1, 2, 3], [4, 5, 6], [1, 2]]

In [23]:
np.array(unlisted)

array([list([1, 2, 3]), list([4, 5, 6]), list([1, 2])], dtype=object)

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [33]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<p><b> if we have one dimenional array then we should have one square bracket; if dealing with two dimension array then two square bracket and for three dimensional we have three square brackets </b></p>

<p><b><h3>"linspace"</h3> is used to create evenly distributed list containing three parameters start,stop, and how many points/count you need </b></p>

In [35]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

<h3> "linspace" and "arange" is different; third parameter of arange say how much step size you need whereas linspace say how many points you need </h3>

<p> Identity Matrix takes one argument : syntax <h3> np.eye(4) </h3> ; In this you will find combination of zeroes and ones in two dimensional array in square matrix having diagonal element is "1" and rest "zero" </p>

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<h3>"Random library to print random numbers"</h3>

In [37]:
np.random.rand(3)

array([0.70312004, 0.4032341 , 0.15516347])

In [38]:
np.random.rand(3,4)

array([[0.1766571 , 0.44374749, 0.40714319, 0.26470227],
       [0.66771335, 0.35908149, 0.64469872, 0.36286857],
       [0.02211338, 0.92825613, 0.42778831, 0.30324778]])

<p><b>random. randn generates samples from the normal distribution, while numpy. random. rand from uniform (in range [0,1))</b></p>

In [40]:
np.random.randn(3,4)

array([[-1.01488641, -0.85946396,  1.28811621,  0.31902007],
       [-1.72589475,  0.32728898, -1.50241726, -0.69156887],
       [-0.80528902, -1.82746412, -0.24785392, -1.37636204]])

In [43]:
np.random.randint(2,50)

12

<p><b> Randint has lower and upper limit which not include higher limit while throwing data. Also, we can put a number that how many random numbers we need from a low,high limit </b></p>

In [45]:
np.random.randint(2,50,10)

array([41, 49, 11, 35,  3, 38,  5, 11, 21, 19])

In [46]:
np.random.randint(2,5,10)

array([4, 4, 4, 3, 3, 3, 4, 4, 2, 4])

In [87]:
arr=np.arange(25)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

<p><b>reshape function used for reshaping existing number/same data into matrix</b></p>

In [89]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
arr.shape

(25,)

In [79]:
ranarr=np.random.randint(0,50,10)

In [80]:
ranarr

array([15, 30, 17, 15,  3, 24, 12,  5, 14,  4])

<p><b> "min", "max" function to find maximum and minimum value in array ; to find index of min ,max , "argmax" and "argmin" use ANd, "dtype" says what type of array is.</b></p>

In [81]:
ranarr.max()

30

In [82]:
ranarr.min()

3

In [83]:
ranarr.argmax()

1

In [84]:
ranarr.argmin()

4

In [86]:
ranarr.dtype

dtype('int32')

<h3> to copy an array , we can use "copy" function and to replace existing data, we can use slicing as in example </h3>

In [94]:
list_arr=np.arange(0,11)

In [95]:
list_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
list_arr[:4]=99

In [97]:
list_arr

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [98]:
list_arr[:4]

array([99, 99, 99, 99])

In [99]:
list_copy=list_arr.copy()

In [100]:
list_copy

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [101]:
list_arr

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [102]:
new_array=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [103]:
new_array

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
new_array[0][0]

5

In [105]:
new_array[1][2]

30

In [154]:
new_array[1:,2:]

array([[30],
       [45]])

In [107]:
new_array[0,0]

5

In [151]:
new_array[:2][1:]

array([[20, 25, 30]])

In [145]:
new_array[:2,1:]

array([[10, 15],
       [25, 30]])

In [155]:
check_array=np.arange(0,11)

In [156]:
check_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
bool_arr= check_array >5

In [158]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [160]:
check_array[bool_arr]

array([ 6,  7,  8,  9, 10])

<p><b> we can also write it in other ways ; Conditional Array </b></p>

In [161]:
check_array[check_array > 5]

array([ 6,  7,  8,  9, 10])

<h3> Addition of two array </h3>

In [162]:
one_arr=np.arange(0,11)

In [163]:
one_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [164]:
one_arr + one_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [165]:
one_arr - one_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [166]:
one_arr * one_arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [167]:
one_arr / one_arr

C:\Users\esrijyo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [168]:
1 / arr

C:\Users\esrijyo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667])

<h3> Scalar array </h3>

In [169]:
np.max(arr)

24

In [170]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [171]:
np.min(arr)

0

In [172]:
arr.min()

0

In [173]:
arr.max()

24

In [174]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [175]:
np.log(arr)

C:\Users\esrijyo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [177]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [178]:
np.exp(arr
      )

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

<h1>Exercise NumPy</h1>

In [182]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [196]:
np.random.random(1)

array([0.87327853])

In [204]:
np.random.randn(25)

array([-0.23059531,  1.62116166, -0.36679988,  0.71337878, -0.54229451,
       -1.32555317,  0.66798358, -0.97917468,  0.49693271, -0.10199283,
        0.98475141, -0.02209458, -0.91636426,  2.79742962,  0.18851899,
        1.23844872, -0.93098228,  0.71940853,  0.9123255 , -0.33742284,
        0.06514867,  0.36601626, -0.24592623,  0.48395793,  1.02046515])

In [215]:
np.random.rand(10,10)



array([[0.46398419, 0.06838764, 0.86608753, 0.82357565, 0.30388513,
        0.25376547, 0.76872484, 0.90970666, 0.56577197, 0.87350444],
       [0.48605606, 0.33577712, 0.46518734, 0.76703013, 0.77850268,
        0.32398827, 0.22970726, 0.18012591, 0.61681074, 0.29802162],
       [0.66379675, 0.12415094, 0.65507246, 0.04753359, 0.51201016,
        0.84755954, 0.65312807, 0.55830416, 0.61334231, 0.89296713],
       [0.11293884, 0.97084583, 0.39671196, 0.9741005 , 0.79186287,
        0.39353162, 0.06542516, 0.37934754, 0.82340665, 0.58596341],
       [0.23958654, 0.2037296 , 0.45716603, 0.12652995, 0.4450516 ,
        0.99210527, 0.59069319, 0.44521534, 0.83033281, 0.77472266],
       [0.50061262, 0.5397526 , 0.97389498, 0.31917341, 0.0094132 ,
        0.32448548, 0.11892424, 0.1008835 , 0.05219557, 0.82228849],
       [0.14534559, 0.33202222, 0.43213344, 0.7994781 , 0.25403964,
        0.83525228, 0.17329304, 0.19307981, 0.61522265, 0.06080545],
       [0.75233511, 0.45567489, 0.9659959

In [214]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [225]:
from nltk import flatten

In [216]:
new_li=[[1,2,3],[4,5,6],[7,8,9]]

In [217]:
new_li

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [226]:
flatten(new_li)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [227]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [238]:
# BE ABLE TO SEE THE OUTPUT ANY MORE
new=np.arange(12,26)
new
index=[4,9]
new_array=np.delete(new,index)
mast=new_array.reshape(3,4)

In [239]:
mast

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [249]:
mast[1:2,3:]

array([[20]])

21

In [4]:
dir(np)


['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad